### ISSUE TITLE
Unable to locate message source for category 'extensions/yii2-settings/settings'.

### ISSUE THREAD

**Issue by uniqby** [phemellc/yii2-settings#11]
my bad, del

**Comment by maituanmte** [comment]
Hi. I have same error. How can you fix it?

**Comment by arisk** [comment]
The translations should work by default if you're using the module. If you're not using the module then consider extending from `BaseSetting` which doens't use translations.

**Comment by maituanmte** [comment]
@arisk Hi arisk. I take configuration as instruction like that
'modules' => [
        'settings' => [
            'class' => 'pheme\settings\Module',
            'sourceLanguage' => 'vn'
        ],
    ],

but nothing work. Is it right?

**Comment by maituanmte** [comment]
@arisk It is ok now. Thank you.

**Comment by arisk** [comment]
Can you post the solution to your problem? It might help others. Thanks!

**Comment by maituanmte** [comment]
/backend/web/index.php?r=settings%2Fdefault%2Findex

The link should contain the module. I think you should contain instruction about translation when they don't use default setting module.php. Module::t(...) can not be used if not.

I just config translation extensions/yii2-settings/settings again.
