### ISSUE TITLE
Add custom translation and views

### ISSUE THREAD

**Issue by ZAYEC77** [phemellc/yii2-settings#15]
How can I add a custom translation for this module?

**Comment by arisk** [comment]
Hi. You need to create the translation directory and file. Please see the `messages` directory for an example. If you like you can submit your translation as a pull request for others to use. For more details please see the Yii2 translation docs. http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html

**Comment by ZAYEC77** [comment]
@arisk, thanks. And what about overriding views?

**Comment by arisk** [comment]
You're welcome. You can override the views by using a custom theme or alternatively you can fork the project and add your own custom views.

**Comment by ZAYEC77** [comment]
@arisk thank you
