### ISSUE TITLE
Table Prefix

### ISSUE THREAD

**Issue by xenolOnline** [phemellc/yii2-settings#24]
Hello,  method tableName() in Setting model not return table name with prefix. I think this right version:
public static function tableName()
    {
        return '{{%settings}}';
    }

Thank you.

**Comment by arisk** [comment]
Please look at the model class more carefully. It does account for the table prefix. Thanks

**Comment by xenolOnline** [comment]
Hello, it is strange. I see throw github, that it is contain table prefix, but if I install extension from composer - it will be without prefix.

**Comment by arisk** [comment]
You might need to change your minimum stability to `dev` that should pull in the latest changes.
