### ISSUE TITLE
How to use type array?

### ISSUE THREAD

**Issue by schmunk42** [phemellc/yii2-settings#32]
I couldn't figure it out, how can I write and read array via PHP code and WebUI?
Could you add an example to the docs?

**Comment by arisk** [comment]
Currently there's no support for settings to be arrays. I guess we could check if `gettype` returns `array` and serialize it before storing it in the DB. Another option could be JSON?
For the WebUI part any suggestions are welcome.

**Comment by schmunk42** [comment]
JSON for arrays would be fine.

Maybe of interest...
This is a great JSON editor: https://github.com/DevGroup-ru/yii2-jsoneditor
For string fields, this would be nice: https://github.com/trntv/yii2-aceeditor
Here's a wip JSON validator: https://github.com/dmstr/yii2-validators/blob/master/src/JsonValidator.php

**Comment by arisk** [comment]
Thanks for the suggestions. I'll look into them.
