### ISSUE TITLE
How to disable cache?

### ISSUE THREAD

**Issue by webadequate** [phemellc/yii2-settings#36]
I Have a problem: 
I setting up parameters via Backend application and using the same parameters in Frontend side but caching saving old values

**Comment by arisk** [comment]
If you set the `cache` and/or `frontCache` configuration to null that should disable caching all together.

**Comment by webadequate** [comment]
Did 'cache' to null. It works.
ps. wich the diffirence between cache and frontCache?

**Comment by arisk** [comment]
It's for the advanced application template. Since it contains 2 separate applications and hence 2 different cache components, some users were finding that clearing the cache wouldn't update the values in their front-end app.
