### ISSUE TITLE
Invalid type when set type is "email"

### ISSUE THREAD

**Issue by hoksilato** [phemellc/yii2-settings#61]
I got error when set a setting's type is "email".

It seems PHP `[settype](http://php.net/manual/en/function.settype.php)` function doesn't support `email` type.

```
Possibles values of type are:

"boolean" (or, since PHP 4.2.0, "bool")
"integer" (or, since PHP 4.2.0, "int")
"float" (only possible since PHP 4.2.0, for older versions use the deprecated variant "double")
"string"
"array"
"object"
"null" (since PHP 4.2.0)
```

**Comment by arisk** [comment]
You can use string for email.

**Comment by hoksilato** [comment]
Yes, I'm using string for the email. But I think should remove `email` from the types list in creating page.
